- name: SSH and git pull (debug)
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.MAC_HOST }}
    username: ${{ secrets.MAC_USER }}
    key: ${{ secrets.MAC_SSH_KEY }}
    port: ${{ secrets.MAC_PORT }}
    debug: true
    timeout: 60s
    command_timeout: 10m
    script: |
      whoami
      hostname
      cd ~/develop/idea-lab/idea-lab
      git fetch --all
      git reset --hard origin/main
