name: Pull on push

on:
  push:
    branches:
      - main

jobs:
  pull-mac:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Git pull
        run: |
          cd ~/develop/idea-lab/idea-lab
          git fetch --all
          git reset --hard origin/main

  pull-windows:
    runs-on: [self-hosted, Windows]
    defaults:
      run:
        shell: bash  # Git Bash使用
    steps:
      - name: Git pull
        run: |
          cd "$USERPROFILE/develop/idea-lab/idea-lab"
          git fetch --all
          git reset --hard origin/main